replicaCount: 2

image:
  repository: 893089245803.dkr.ecr.eu-central-1.amazonaws.com/docker-images
  tag: 99fc3772667977943c03ec4d792466825491476e
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  ingressClassName: alb

  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    
  host: frontend.maorcloud.com