replicas: 1

persistence:
  enabled: false

service:
  type: ClusterIP

ingress:
  enabled: true

  ingressClassName: alb

  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /api/health

  hosts:
    - grafana.maorcloud.com

grafana.ini:
  server:
    root_url: https://grafana.mylabcompany.com

  auth.generic_oauth:
    enabled: true
    name: Keycloak
    allow_sign_up: true

    client_id: grafana

    scopes: openid email profile roles

    auth_url: http://10.100.102.25:8080/realms/grafana-lab/protocol/openid-connect/auth
    token_url: http://85.65.234.196:8080/realms/grafana-lab/protocol/openid-connect/token
    api_url: http://85.65.234.196:8080/realms/grafana-lab/protocol/openid-connect/userinfo

    login_attribute_path: preferred_username
    email_attribute_path: email

    role_attribute_path: "contains(resource_access.grafana.roles[*], 'admin') && 'Admin' || contains(resource_access.grafana.roles[*], 'editor') && 'Editor' || contains(resource_access.grafana.roles[*], 'viewer') && 'Viewer' || 'None'"

    role_attribute_strict: true
    skip_org_role_sync: false

envValueFrom:
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
    secretKeyRef:
      name: grafana-oidc
      key: client-secret

  GF_SECURITY_ADMIN_USER:
    secretKeyRef:
      name: grafana-credentials
      key: username

  GF_SECURITY_ADMIN_PASSWORD:
    secretKeyRef:
      name: grafana-credentials
      key: password