replicas: 1

persistence:
  enabled: false

service:
  type: ClusterIP

ingress:
  enabled: true

  ingressClassName: alb

  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

  hosts:
    - grafana.mylabcompany.com