apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: externalsecret
  namespace: argocd

spec:
  project: default

  sources:
    # Helm Chart
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets

      helm:
        valueFiles:
          - $values/values/externalsecret/values.yaml

    # ה-GitOps repository שלנו
    - repoURL: https://github.com/Sass0nX/mylabcompany.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secret

  syncPolicy:
    automated:
      prune: true
      selfHeal: true